## Startup & config ###
after-startup-command = [
]

start-at-login = true

######################
### Style & Layout ###
######################
# Normalizations.
# See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
accordion-padding = 0

# Mouse follows focus when focused monitor changes
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[gaps]
outer.top = [{ monitor.'built-in.*' = 0 }, 0]
outer.right      = 0
outer.bottom     = 0
outer.left       = 0
inner.horizontal = 1 # gap beetween windows on Horizontal layout (window in vertival mode)
inner.vertical   = 1  # same but when windows are on Horizontal mode (vertival layout)

###################
### Key Mapping ###
###################
[key-mapping.key-notation-to-key-code]
alpha     = "q"          # A -> Q
bravo     = "b"          # B -> B
charlie   = "c"          # C -> C
delta     = "d"          # D -> D
echo      = "e"          # E -> E
foxtrot   = "f"          # F -> F
golf      = "g"          # G -> G
hotel     = "h"          # H -> Hgmkkmkmkmkmk
india     = "i"          # I -> I
juliett   = "j"          # J -> J
kilo      = "k"          # K -> K
lima      = "l"          # L -> L
november  = "n"          # N -> N should be ,
mike      = 'semicolon'  # M -> ;
oscar     = "o"          # O -> O
papa      = "p"          # P -> P
quebec    = "a"          # Q -> A
romeo     = "r"          # R -> R
sierra    = "s"          # S -> S
tango     = "t"          # T -> T
unicorn   = "u"          # U -> U
victor    = "v"          # V -> V
whiskey   = "q"          # W -> Q
xray      = "x"          # X -> X
yankee    = "y"          # Y -> Y
zulu      = "w"          # Z -> W

#######################################################################################################
## All possible keys:
## - Letters.        a, b, c, ..., z
#
## - Numbers.        0, 1, 2, ..., 9
#
## - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
## - F-keys.         f1, f2, ..., f20
#
## - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
##                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
##                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
##                   sectionSign (ISO keyboards only, european keyboards only)
#
## - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
##                   keypadMinus, keypadMultiply, keypadPlus
#
## - Arrows.         left, down, up, right
#######################################################################################################


#########################
### Workspaces config ###
#########################
# persistent-workspaces = ['1','2','3','4','5']
# Assign certain workspaces to
# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
1 = ['M27Q'] # Front screen
2 = ['M27Q'] # Main
3 = ['Built-in'] # Front screen
4 = ['AORUS'] # Right screen
5 = ['AORUS'] # Right screen

####################
### Main Bndings ###
####################
# - Focus Workspaces / Monitors
# - Focus windows
# - Send window/node to another workspace
# - Launch Apps
[mode.main.binding]
# Quick shortcuts
alt-space     = 'workspace 2' # Go to terminal
alt-tab       = 'workspace-back-and-forth'
alt-enter     = 'fullscreen' # Toggle full screen

# Switch window focus
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-left  = [ 'focus dfs-prev --boundaries-action wrap-around-the-workspace' ]
alt-ctrl-right = [ 'focus dfs-next --boundaries-action wrap-around-the-workspace' ]

# Switch workspaces
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-alt-right = ['workspace next --wrap-around']
cmd-alt-left  = ['workspace prev --wrap-around']

# Switch monitor focus
#https://nikitabobko.github.io/AeroSpace/commands#focus-monitor
# focus-monitor
cmd-alt-ctrl-right = ['focus-monitor --wrap-around next'
#'move-mouse monitor-lazy-center'
]
cmd-alt-ctrl-left  = ['focus-monitor --wrap-around prev']

# Layouts management
shift-alt-ctrl-slash = ['balance-sizes']
cmd-alt-ctrl-foxtrot = ['layout floating tiling']
cmd-alt-ctrl-tango = ['layout tiles accordion']
cmd-alt-ctrl-victor = ['layout horizontal vertical']

# Move windows in the given direction
# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-shift-up    = 'move up'
cmd-shift-left  = 'move left'
cmd-shift-down  = 'move down'
cmd-shift-right = 'move right'

# Merge nodes
# See: https://nikitabobko.github.io/AeroSpace/commands#join-with
cmd-alt-shift-up    = ['join-with left' ]
cmd-alt-shift-left  = ['join-with down' ]
cmd-alt-shift-down  = ['join-with up' ]
cmd-alt-shift-right = ['join-with right']

# Resizing
ctrl-shift-down = 'resize smart -20'
ctrl-shift-up = 'resize smart +20'

# Mods
cmd-alt-ctrl-sierra = 'mode service'  # Todo Make a Double tap S shortcut
cmd-alt-ctrl-slash   = 'mode layout'     # Todo Make a Double tap L shortcut

######################
### Layout Bndings ###
######################
# - Reorganize windows
# - Send Window / node to another workspace
# - Send Workspace to another monitor
# - Resize windows (half, quater, full screen
[mode.layout.binding]
esc = ['mode main']
# Switch window focus
alt-ctrl-left  = [ 'focus dfs-prev --boundaries-action wrap-around-the-workspace' ]
alt-ctrl-right = [ 'focus dfs-next --boundaries-action wrap-around-the-workspace' ]

# Move windows in the given direction
# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-up    = 'move up'
shift-left  = 'move left'
shift-down  = 'move down'
shift-right = 'move right'

# Merge nodes
# See: https://nikitabobko.github.io/AeroSpace/commands#join-with
alt-shift-up    = ['join-with left' ]
alt-shift-left  = ['join-with down' ]
alt-shift-down  = ['join-with up' ]
alt-shift-right = ['join-with right']


# Move windows/nodes to other workspaces
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-alt-right = ['move-node-to-workspace next', 'workspace next']
cmd-alt-left  = ['move-node-to-workspace prev', 'workspace prev']

# Move nodes to other monitor by direction
#See https://nikitabobko.github.io/AeroSpace/commands#move-node-to-monitor
cmd-alt-ctrl-left   = ['move-node-to-monitor left', 'focus-monitor left' ]
cmd-alt-ctrl-right  = ['move-node-to-monitor right', 'focus-monitor right']
cmd-alt-ctrl-up     = ['move-node-to-monitor up', 'focus-monitor up']
cmd-alt-ctrl-down   = ['move-node-to-monitor down', 'focus-monitor down']

# Toggle between floating and tiling layout
cmd-alt-ctrl-foxtrot = ['layout floating tiling']

# Toggle between accordion and tiling layout
cmd-alt-ctrl-tango = ['layout tiles accordion']

# Toggle between horizontal vertival layout
cmd-alt-ctrl-hotel = ['layout horizontal vertical']

# reset workspace layout
cmd-alt-ctrl-romeo = ['flatten-workspace-tree']

ctrl-down = 'resize smart -50'
ctrl-up = 'resize smart +50'
shift-ctrl-down = 'resize smart -10'
shift-ctrl-up = 'resize smart +10'


#######################
### Service Bndings ###
#######################
[mode.service.binding]
esc = ['reload-config', 'mode main']

backspace = ['close-all-windows-but-current', 'mode main']


###########################
# Hooks & Event           #
###########################

[[on-window-detected]]
    if.app-id = 'com.github.wez.wezterm'
    check-further-callbacks = true
    run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
    if.app-id = 'com.microsoft.VSCode'
    run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
    if.app-id = 'com.jetbrains.datagrip'
    run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
    if.app-id = 'com.postmanlabs.mac'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-id = 'company.thebrowser.Browser'
    run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
    if.app-id = 'notion.id'
    run = ['layout tiling', 'move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = ['move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'com.deezer.deezer-desktop'
    run = ['move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'com.apple.Music'
    run = ['move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = ['move-node-to-workspace 5']

[[on-window-detected]]
    if.app-id = 'ai.elementlabs.lmstudio'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-id = 'teleportlabs.com.Dayflow'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-id = 'com.dashlane.dashlaneph1final'
    run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
    if.app-id = 'net.battle.app'
    check-further-callbacks = true
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.gog.galaxy'
    check-further-callbacks = true
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.heroicgameslauncher.hgl'
    check-further-callbacks = true
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.codeweavers.CrossOver'
    check-further-callbacks = true
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'unity.Blizzard Entertainment.Hearthstone'
    check-further-callbacks = true
    run = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
    if.app-id = 'com.google.chrome.for.testing'
    check-further-callbacks = true
    run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = ['layout floating', 'move-node-to-workspace 3']


